# this is the build file for project simp_lang
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
RC=/home/danielboll/.cargo/bin/rustc
AS=/usr/bin/gcc
GC=/usr/bin/go
CU=/usr/bin/clang
MM=/usr/bin/gcc
ZC=/usr/bin/zig
MXX=/usr/bin/gcc
CXX=/usr/bin/gcc
CC=/usr/bin/gcc

GCLD=/usr/bin/go
ZCLD=/usr/bin/zig
LD=/usr/bin/g++
RCLD=/home/danielboll/.cargo/bin/rustc
ZCSH=/usr/bin/zig
SH=/usr/bin/g++
RCSH=/home/danielboll/.cargo/bin/rustc
GCAR=/usr/bin/go
AR=/usr/bin/ar
ZCAR=/usr/bin/zig
RCAR=/home/danielboll/.cargo/bin/rustc


simp_lang-lib_CCFLAGS=-m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -Ibuild/.gens/simp_lang-lib/linux/x86_64/release/rules/yacc_yacc -isystem /home/danielboll/.xmake/packages/g/gtest/1.12.1/77b9096bc4b34d9282f672d36b015ba9/include -std=c17 -DNDEBUG
simp_lang-lib_ARFLAGS=-cr
simp_lang_CCFLAGS=-m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -isystem /home/danielboll/.xmake/packages/g/gtest/1.12.1/77b9096bc4b34d9282f672d36b015ba9/include -std=c17 -DNDEBUG
simp_lang_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -L/home/danielboll/.xmake/packages/g/gtest/1.12.1/77b9096bc4b34d9282f672d36b015ba9/lib -s -lsimp_lang-lib -lfmt -lgtest_main -lgmock -lgtest -lpthread

default:  simp_lang-lib simp_lang

all:  simp_lang-lib simp_lang

.PHONY: default all  simp_lang-lib simp_lang

precmds_simp_lang-lib:
	@mkdir -p build/.gens/simp_lang-lib/linux/x86_64/release/rules/yacc_yacc
	$(VV)/usr/bin/bison -d -o build/.gens/simp_lang-lib/linux/x86_64/release/rules/yacc_yacc/parser.tab.c src/simp_lang/parser.y
	@mkdir -p build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/yacc_yacc
	$(VV)/usr/bin/gcc -c -m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -Ibuild/.gens/simp_lang-lib/linux/x86_64/release/rules/yacc_yacc -isystem /home/danielboll/.xmake/packages/g/gtest/1.12.1/77b9096bc4b34d9282f672d36b015ba9/include -std=c17 -DNDEBUG -o build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o build/.gens/simp_lang-lib/linux/x86_64/release/rules/yacc_yacc/parser.tab.c
	@mkdir -p build/.gens/simp_lang-lib/linux/x86_64/release/rules/lex_yacc
	$(VV)/usr/bin/flex -o build/.gens/simp_lang-lib/linux/x86_64/release/rules/lex_yacc/lexer.c src/simp_lang/lexer.l
	@mkdir -p build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/lex_yacc
	$(VV)/usr/bin/gcc -c -m64 -fvisibility=hidden -O3 -I/usr/include -I/usr/local/include -Iinclude -Ibuild/.gens/simp_lang-lib/linux/x86_64/release/rules/yacc_yacc -isystem /home/danielboll/.xmake/packages/g/gtest/1.12.1/77b9096bc4b34d9282f672d36b015ba9/include -std=c17 -DNDEBUG -o build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o build/.gens/simp_lang-lib/linux/x86_64/release/rules/lex_yacc/lexer.c

simp_lang-lib: build/linux/x86_64/release/libsimp_lang-lib.a
build/linux/x86_64/release/libsimp_lang-lib.a: precmds_simp_lang-lib build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/y.tab.c.o build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/simp_lang.c.o build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/lex.yy.c.o build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o
	@echo linking.release libsimp_lang-lib.a
	@mkdir -p build/linux/x86_64/release
	$(VV)$(AR) $(simp_lang-lib_ARFLAGS) build/linux/x86_64/release/libsimp_lang-lib.a build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/y.tab.c.o build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/simp_lang.c.o build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/lex.yy.c.o build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o

build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/y.tab.c.o: precmds_simp_lang-lib src/simp_lang/y.tab.c
	@echo ccache compiling.release src/simp_lang/y.tab.c
	@mkdir -p build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang
	$(VV)$(CC) -c $(simp_lang-lib_CCFLAGS) -o build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/y.tab.c.o src/simp_lang/y.tab.c

build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/simp_lang.c.o: precmds_simp_lang-lib src/simp_lang/simp_lang.c
	@echo ccache compiling.release src/simp_lang/simp_lang.c
	@mkdir -p build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang
	$(VV)$(CC) -c $(simp_lang-lib_CCFLAGS) -o build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/simp_lang.c.o src/simp_lang/simp_lang.c

build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/lex.yy.c.o: precmds_simp_lang-lib src/simp_lang/lex.yy.c
	@echo ccache compiling.release src/simp_lang/lex.yy.c
	@mkdir -p build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang
	$(VV)$(CC) -c $(simp_lang-lib_CCFLAGS) -o build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/lex.yy.c.o src/simp_lang/lex.yy.c

simp_lang: build/linux/x86_64/release/simp_lang
build/linux/x86_64/release/simp_lang: build/linux/x86_64/release/libsimp_lang-lib.a build/.objs/simp_lang/linux/x86_64/release/standalone/main.c.o
	@echo linking.release simp_lang
	@mkdir -p build/linux/x86_64/release
	$(VV)$(LD) -o build/linux/x86_64/release/simp_lang build/.objs/simp_lang/linux/x86_64/release/standalone/main.c.o $(simp_lang_LDFLAGS)

build/.objs/simp_lang/linux/x86_64/release/standalone/main.c.o: standalone/main.c
	@echo ccache compiling.release standalone/main.c
	@mkdir -p build/.objs/simp_lang/linux/x86_64/release/standalone
	$(VV)$(CC) -c $(simp_lang_CCFLAGS) -o build/.objs/simp_lang/linux/x86_64/release/standalone/main.c.o standalone/main.c

clean:  clean_simp_lang-lib clean_simp_lang

clean_simp_lang-lib: 
	@rm -rf build/linux/x86_64/release/libsimp_lang-lib.a
	@rm -rf build/linux/x86_64/release/simp_lang-lib.sym
	@rm -rf build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/y.tab.c.o
	@rm -rf build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/simp_lang.c.o
	@rm -rf build/.objs/simp_lang-lib/linux/x86_64/release/src/simp_lang/lex.yy.c.o
	@rm -rf build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/yacc_yacc/parser.tab.c.o
	@rm -rf build/.objs/simp_lang-lib/linux/x86_64/release/gens/rules/lex_yacc/lexer.c.o

clean_simp_lang:  clean_simp_lang-lib
	@rm -rf build/linux/x86_64/release/simp_lang
	@rm -rf build/linux/x86_64/release/simp_lang.sym
	@rm -rf build/.objs/simp_lang/linux/x86_64/release/standalone/main.c.o

